---
- name: install dependencies
  apt:
    name: "{{ unifi_package_dependencies }}"
    state: present
  become: yes

- name: install ubnt apt key
  apt_key:
    keyserver: "{{ unifi_repo_key_server }}"
    id: "{{ unifi_repo_key_id }}"
  become: yes

- name: install ubnt apt repository
  apt_repository:
    filename: "{{ unifi_repo_name }}"
    repo: "{{ unifi_repo_url }}"
    state: "{{ unifi_repo_state }}"
  become: yes
  when: ansible_os_family == "Debian"

- name: install java packages
  apt:
    allow_unauthenticated: yes
    name: "{{ unifi_java_packages }}"
    state: "{{ unifi_packages_state }}"
    update_cache: yes
  become: yes
  notify:
    - restart unifi

- name: install unifi-controller packages
  apt:
    allow_unauthenticated: yes
    name: "{{ unifi_packages }}"
    state: "{{ unifi_packages_state }}"
    update_cache: yes
  become: yes
  notify:
    - restart unifi
    - stop mongodb

- name: update snappy java
  get_url:
    url: "{{ unifi_java_snappy_url }}"
    checksum: "{{ unifi_java_snappy_checksum }}"
    dest: "{{ unifi_java_snappy_file }}"
  become: yes
  notify:
    - restart unifi

- name: manage services
  service:
    name: "{{ item }}"
    state: "{{ unifi_services_state }}"
    enabled: "{{ unifi_services_enabled }}"
  become: yes
  with_items: "{{ unifi_services }}"

- name: install golift apt key
  apt_key:
    keyserver: "{{ unifi_poller_repo_key_server }}"
    id: "{{ unifi_poller_repo_key_id }}"
  become: yes

- name: install golift apt repository
  apt_repository:
    filename: "{{ unifi_poller_repo_name }}"
    repo: "{{ unifi_poller_repo_url }}"
    state: "{{ unifi_poller_repo_state }}"
  become: yes
  when: ansible_os_family == "Debian"

- name: install unifi-poller 
  apt:
    name: "{{ unifi_poller_packages }}"
    state: present
  become: yes

- name: update unifi-poller config file
  template:
    src: "{{ unifi_poller_config_tpl }}"
    dest: "{{ unifi_poller_config_dest }}"
    owner: root
    group: unifi
    mode: u=rw,g=rw,o=r

  become: yes
  notify:
    - restart unifi-poller