unifi_package_dependencies:
  - gnupg
  - apt-transport-https
unifi_packages:
  - unifi
unifi_packages_state: present
unifi_repo_name: unifi
unifi_repo_url: deb http://www.ui.com/downloads/unifi/debian stable ubiquiti
unifi_repo_state: present
unifi_repo_key_server: https://dl.ui.com/unifi/unifi-repo.gpg
unifi_repo_key_id: 4A228B2D358A5094178285BE06E85760C0A52C50
unifi_services:
- unifi
unifi_services_state: started
unifi_services_enabled: yes
unifi_java_packages: openjdk-8-jre-headless
unifi_java_home: /usr/lib/jvm/java-8-openjdk-amd64
unifi_java_snappy_url: https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.2.6/snappy-java-1.1.2.6.jar
unifi_java_snappy_checksum: sha256:61f7bc4076be0320ab4ef076fb6d83e3f649c3caf9ffb6031654a73f9c23732f
unifi_java_snappy_file: /usr/lib/unifi/lib/snappy-java-1.0.5.jar

unifi_poller_packages:
  - unifi
unifi_poller_packages_state: present
unifi_poller_repo_name: unifi_poller 
unifi_poller_repo_url: deb https://dl.bintray.com/golift/ubuntu buster main
unifi_poller_repo_state: present
unifi_poller_repo_key_server: https://golift.io/gpgkey
unifi_poller_repo_key_id: B93DD66EF98E54E2EAE025BA0166AD34ABC5A57C
unifi_poller_services:
- unifi-poller
unifi_poller_services_state: started
unifi_poller_services_enabled: yes
unifi_poller_config_tpl: "up.conf.j2"
unifi_poller_config_dest: "/etc/unifi-poller/up.conf"