---
- name: restart unifi
  service:
    name: "{{ item }}"
    state: restarted
  become: yes
  with_items: "{{ unifi_services }}"

- name: stop mongodb
  service:
    name: "{{ item }}"
    state: stopped
  become: yes
  with_items: "{{ unifi_mongodb_services }}"

- name: restart unifi-poller
  service:
    name: "{{ item }}"
    state: restarted
  become: yes
  with_items: "{{ unifi_poller_services }}"